<a href="https://colab.research.google.com/github/Carchives03/NYCSummonsPracticeData/blob/main/NYCSummonsDataPracticeAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd


df = pd.read_csv("summonsdata.csv")
print(df.head())

   SUMMONS_KEY SUMMONS_DATE               OFFENSE_DESCRIPTION  \
0    298767983   12/31/2024                DISORDERLY CONDUCT
1    298704187   12/31/2024                   IMPROPER PLATES
2    298787872   12/31/2024                          TRESPASS
3    298724988   12/31/2024     FEDERAL MOTOR VEH. SAFETY REG
4    298704460   12/31/2024  POSSESSION OF ALCOHOL BY A MINOR

  LAW_SECTION_NUMBER     LAW_DESCRIPTION SUMMONS_CATEGORY_TYPE AGE_GROUP  \
0              240.2           Penal Law    DISORDERLY CONDUCT     45-64
1                402                 VTL                   VTL     18-24
2             140.05           Penal Law              TRESPASS     25-44
3             CFR 49  NYS Transportation             NYS TRANS   UNKNOWN
4               65-C              (null)                (null)     18-24

      SEX                      RACE  JURISDICTION_CODE       BORO  \
0       M            WHITE HISPANIC                  0  MANHATTAN
1       M  ASIAN / PACIFIC ISLANDER                  0      BRONX
2       F            BLACK HISPANIC                  2  MANHATTAN
3  (null)                    (null)                  0   BROOKLYN
4       M                     WHITE                  0  MANHATTAN

   PRECINCT_OF_OCCUR  X_COORDINATE_CD  Y_COORDINATE_CD   Latitude  Longitude  \
0                 14           985927           213077  40.751523 -73.993947
1                 49          1020823           249562  40.851589 -73.867801
2                 32           998922           235604  40.813352 -73.946996
3                 94          1001547           203048  40.723980 -73.937597
4                  6           984439           204595  40.728254 -73.999318

                                        Lon_Lat
0  POINT (-73.99394730218468 40.75152348693427)
1  POINT (-73.86780058180116 40.85158922344624)
2                  POINT (-73.946996 40.813352)
3  POINT (-73.93759674847603 40.72397961334044)
4                  POINT (-73.999318 40.728254)

## Sampling Data

In [ ]:
# Grabing Random Sample of Data
df.sample(20)

,SUMMONS_KEY,SUMMONS_DATE,OFFENSE_DESCRIPTION,LAW_SECTION_NUMBER,LAW_DESCRIPTION,SUMMONS_CATEGORY_TYPE,AGE_GROUP,SEX,RACE,JURISDICTION_CODE,BORO,PRECINCT_OF_OCCUR,X_COORDINATE_CD,Y_COORDINATE_CD,Latitude,Longitude,Lon_Lat
231764,247632918,07/06/2022,FEDERAL MOTOR VEH. SAFETY REG,CFR 49,NYS Transportation,NYS TRANS,UNKNOWN,(null),(null),0,BRONX,45,1037925,237116,40.817341,-73.806082,POINT (-73.80608221 40.81734122)
215180,252440976,10/11/2022,FEDERAL MOTOR VEH. SAFETY REG,CFR 49,NYS Transportation,NYS TRANS,UNKNOWN,(null),(null),0,QUEENS,103,1042505,194808,40.701189,-73.789901,POINT (-73.789901 40.701189)
218146,251543748,09/24/2022,ALCOHOLIC BEVERAGE IN PUBLIC,10-125(2B),(null),(null),45-64,M,WHITE HISPANIC,0,QUEENS,115,1021164,213514,40.752646,-73.866766,POINT (-73.866766 40.752646)
96874,279173047,12/18/2023,FEDERAL MOTOR VEH. SAFETY REG,CFR 49,NYS Transportation,NYS TRANS,UNKNOWN,(null),(null),0,STATEN ISLAND,121,942822,166353,40.623188,-74.149238,POINT (-74.1492376947323 40.6231883776008)
20596,294361424,10/04/2024,FEDERAL MOTOR VEH. SAFETY REG,CFR 49,NYS Transportation,NYS TRANS,UNKNOWN,(null),(null),0,BRONX,45,1029379,236734,40.816341,-73.836960,POINT (-73.83695981253422 40.81634053709817)
84413,281767360,02/06/2024,OTHER TRANSIT REG,9999,ABC,OTHER ABC,25-44,M,WHITE,0,BROOKLYN,83,1004424,193538,40.697881,-73.927245,POINT (-73.92724476 40.69788147)
207293,262102094,11/18/2022,PEDESTRIAN WALKING INTO TRAFFIC UNSAFELY,4-04(B)(2),(null),(null),18-24,M,BLACK,0,BROOKLYN,79,998973,186411,40.678320,-73.946919,POINT (-73.94691946 40.67831961)
231437,247765553,07/08/2022,ALCOHOLIC BEVERAGE IN PUBLIC,10-125(2B),(null),(null),25-44,M,ASIAN / PACIFIC ISLANDER,0,QUEENS,108,995086,209002,40.740332,-73.960897,POINT (-73.96089682 40.74033215)
78205,282952457,02/28/2024,OPERATION WHILE REGISTRATION OR PRIVILEGE IS S...,512,(null),(null),45-64,M,BLACK,0,BRONX,41,1014390,235787,40.813805,-73.891116,POINT (-73.8911156357594 40.81380514554565)
18283,294779645,10/12/2024,RED LIGHT (DISOBEY),1111,VTL,VTL,25-44,F,ASIAN / PACIFIC ISLANDER,0,MANHATTAN,17,991780,214662,40.755871,-73.972821,POINT (-73.97282063816039 40.75587086232265)
223130,250206676,08/26/2022,ALCOHOL IN THE PARK,1-05(F) 1,(null),(null),25-44,M,BLACK,0,BROOKLYN,75,1015559,181859,40.665784,-73.887141,POINT (-73.887141 40.665784)
94990,279706943,12/29/2023,DISORDERLY CONDUCT,240.2,Penal Law,DISORDERLY CONDUCT,25-44,M,BLACK,0,MANHATTAN,6,983551,208788,40.739751,-74.002522,POINT (-74.00252241397993 40.73975138823035)
47251,289271259,06/28/2024,ACCEPT ON HAIL,19-507,Administrative Code,TLC,18-24,M,BLACK,0,QUEENS,103,1037559,194576,40.700582,-73.807742,POINT (-73.80774181591707 40.70058232906593)
14860,295445100,10/25/2024,"ENGAGES IN FIGHTING, OR VIOLENT, TUMULTUOUS OR...",240.20(1),(null),(null),18-24,M,BLACK HISPANIC,0,BRONX,44,1006195,240321,40.826275,-73.920705,POINT (-73.920705 40.826275)
77800,283064151,03/01/2024,RECKLESS DRIVING,1212,VTL,VTL,25-44,M,WHITE HISPANIC,2,MANHATTAN,23,1000086,229653,40.797008,-73.942802,POINT (-73.942802 40.797008)
16017,295221860,10/21/2024,RECKLESS DRIVING,1212,VTL,VTL,25-44,F,BLACK,2,BROOKLYN,88,991609,192937,40.696241,-73.973462,POINT (-73.9734616155017 40.69624116875087)
30692,292380697,08/27/2024,RECKLESS DRIVING,1212,VTL,VTL,18-24,M,BLACK,0,BROOKLYN,81,1003897,188279,40.683437,-73.929162,POINT (-73.92916162840565 40.68343728574764)
175555,266600132,04/12/2023,ALCOHOLIC BEVERAGE IN PUBLIC,10-125(2B),(null),(null),25-44,M,BLACK HISPANIC,0,BRONX,41,1013480,239485,40.823961,-73.894384,POINT (-73.894384 40.823961)
224316,249849600,08/19/2022,NOISE (DEVICE),24-220,Administrative Code,NOISE,45-64,M,BLACK,0,QUEENS,104,1006434,201617,40.720043,-73.919968,POINT (-73.919968 40.720043)
58984,287089927,05/17/2024,FAILURE TO COMPLY WITH SIGN,01-03,Park Regs,PARK REGS,18-24,M,WHITE HISPANIC,2,BROOKLYN,79,997364,192889,40.696104,-73.952707,POINT (-73.952707 40.696104)

In [ ]:
# Grabing tail end of DF
df.tail(20)

,SUMMONS_KEY,SUMMONS_DATE,OFFENSE_DESCRIPTION,LAW_SECTION_NUMBER,LAW_DESCRIPTION,SUMMONS_CATEGORY_TYPE,AGE_GROUP,SEX,RACE,JURISDICTION_CODE,BORO,PRECINCT_OF_OCCUR,X_COORDINATE_CD,Y_COORDINATE_CD,Latitude,Longitude,Lon_Lat
259110,238495874,01/01/2022,DISORDERLY CONDUCT,240.2,Penal Law,DISORDERLY CONDUCT,<18,M,BLACK HISPANIC,0,BRONX,50,1012518,256571,40.870857,-73.897791,POINT (-73.89779084 40.87085729)
259111,238496138,01/01/2022,DISORDERLY CONDUCT,240.2,Penal Law,DISORDERLY CONDUCT,18-24,M,WHITE,0,MANHATTAN,7,987296,201153,40.718795,-73.989012,POINT (-73.98901164 40.71879468)
259112,238496136,01/01/2022,DISORDERLY CONDUCT,240.2,Penal Law,DISORDERLY CONDUCT,18-24,M,BLACK,0,BROOKLYN,73,1009519,180676,40.662554,-73.908920,POINT (-73.9089197 40.6625545)
259113,238492972,01/01/2022,DISORDERLY CONDUCT,240.2,Penal Law,DISORDERLY CONDUCT,25-44,M,BLACK,0,BROOKLYN,75,1017119,183909,40.671404,-73.881509,POINT (-73.881509 40.671404)
259114,238521046,01/01/2022,FEDERAL MOTOR VEH. SAFETY REG,CFR 49,NYS Transportation,NYS TRANS,UNKNOWN,(null),(null),0,QUEENS,109,1032198,217060,40.762335,-73.826917,POINT (-73.8269171 40.76233451)
259115,238498330,01/01/2022,CONSUMPTION OF ALCOHOL,10-125,Administrative Code,ALCOHOL,25-44,M,WHITE HISPANIC,0,BROOKLYN,72,984720,179802,40.660192,-73.998305,POINT (-73.998305 40.660192)
259116,238600506,01/01/2022,KNIVES; PUBLIC POSSESSION (BLADE 4 INCHES OR M...,10-133(B),(null),(null),45-64,M,BLACK,0,MANHATTAN,18,989329,217361,40.763281,-73.981664,POINT (-73.981664 40.763281)
259117,238513030,01/01/2022,CONGREGATES WITH OTHER PERSONS IN PUBLIC AND R...,240.20(6),(null),(null),25-44,F,WHITE HISPANIC,0,BRONX,49,1030251,254037,40.863830,-73.833690,POINT (-73.83369 40.86383)
259118,238568957,01/01/2022,DISCON: CREATE HAZARDOUS CONDITION,240.20-7,Penal Law,DISORDERLY CONDUCT,18-24,M,BLACK,2,BRONX,40,1005481,233854,40.808526,-73.923306,POINT (-73.923306 40.808526)
259119,238513036,01/01/2022,NON PAYMENT OF FARE (OTHER),1050.4(A),(null),(null),25-44,M,WHITE,1,MANHATTAN,25,1001526,232252,40.804146,-73.937596,POINT (-73.93759587 40.80414606)
259120,238526499,01/01/2022,ALCOHOLIC BEVERAGE IN PUBLIC,10-125(2B),(null),(null),25-44,M,BLACK,0,BROOKLYN,94,996619,207763,40.736931,-73.955365,POINT (-73.955365 40.736931)
259121,238547199,01/01/2022,UNLICENSED OPERATOR,509,VTL,VTL,18-24,M,BLACK,0,BRONX,52,1011613,255632,40.868283,-73.901067,POINT (-73.9010669 40.86828288)
259122,238497763,01/01/2022,NO FLAME PERMIT FOR CANDLES,105.6,(null),(null),25-44,F,BLACK,0,BROOKLYN,67,1003561,178518,40.656647,-73.930401,POINT (-73.930401 40.656647)
259123,238526850,01/01/2022,MOTOR VEHICLE; ENGINE ON/KEY IN IGNITION (THER...,10-111(A),(null),(null),25-44,M,ASIAN / PACIFIC ISLANDER,0,QUEENS,105,1055007,200298,40.716165,-73.744756,POINT (-73.74475602 40.71616548)
259124,238526745,01/01/2022,POSSESSION OF AIR PISTOL/RIFLE,10-131(B),(null),(null),18-24,F,WHITE HISPANIC,0,QUEENS,104,1010834,197467,40.708638,-73.904114,POINT (-73.90411363 40.70863808)
259125,238522722,01/01/2022,MOTOR VEHICLE; ENGINE ON/KEY IN IGNITION (THER...,10-111(A),(null),(null),25-44,F,ASIAN / PACIFIC ISLANDER,0,QUEENS,108,999474,211676,40.747665,-73.945056,POINT (-73.94505608 40.74766514)
259126,238513031,01/01/2022,"ENGAGES IN FIGHTING, OR VIOLENT, TUMULTUOUS OR...",240.20(1),(null),(null),25-44,F,BLACK,0,BRONX,44,1004057,245519,40.840548,-73.928416,POINT (-73.928416 40.840548)
259127,238496137,01/01/2022,"ENGAGES IN FIGHTING, OR VIOLENT, TUMULTUOUS OR...",240.20(1),(null),(null),25-44,M,BLACK,0,MANHATTAN,7,987296,201153,40.718795,-73.989012,POINT (-73.98901164 40.71879468)
259128,238513029,01/01/2022,CONGREGATES WITH OTHER PERSONS IN PUBLIC AND R...,240.20(6),(null),(null),18-24,M,WHITE HISPANIC,0,BRONX,49,1030251,254037,40.863830,-73.833690,POINT (-73.83369 40.86383)
259129,238526692,01/01/2022,IDLING OF VEHICLE,24-163,Administrative Code,TLC,25-44,M,BLACK,2,BROOKLYN,79,999608,189539,40.686904,-73.944623,POINT (-73.94462298 40.68690417)

## Questions for Analysis

In [ ]:
# Questions for Summons
# 1. Which is their a inequality in the different buroughs.
# 2. What are racial demographics versus the type of chargres
# 3. What level of charge is it. A grouping of the charges. By severity.
# 4. Are there any patterns in charge between gender or race.

# ANALYSIS

GROUPING BY BORO

In [ ]:
# BROOKLYN
# Step 1: Filter the dataset to only Brooklyn, then count offenses by race
brooklyn_df =df[df["BORO"] == "BROOKLYN"]  # select only the rows where the borough is Brooklyn
race_counts_brooklyn = brooklyn_df.groupby("RACE").size()  # group the Brooklyn rows by race and count how many summonses fall in each race group
race_counts_brooklyn = race_counts_brooklyn.reset_index()  # convert the grouped Series back into a regular DataFrame
race_counts_brooklyn.columns = ["RACE", "COUNT"]  # rename the columns for clarity
race_counts_brooklyn = race_counts_brooklyn.sort_values(by="COUNT", ascending=False)  # sort the races from most offenses to fewest
print(race_counts_brooklyn)  # display the resulting table showing race with the most offenses in Brooklyn

                             RACE  COUNT
3                           BLACK  43602
0                          (null)  19840
8                  WHITE HISPANIC  14362
7                           WHITE   6009
4                  BLACK HISPANIC   4177
2        ASIAN / PACIFIC ISLANDER   3118
6                         UNKNOWN    684
1  AMERICAN INDIAN/ALASKAN NATIVE    346
5                           OTHER    157

In [ ]:
# Step 1: Filter Brooklyn data to only Black, Black Hispanic, and White Hispanic, then pivot offense vs race
selected_races = ["BLACK", "BLACK HISPANIC", "WHITE HISPANIC"]  # define the list of race categories to keep
brooklyn_filtered = brooklyn_df[brooklyn_df["RACE"].isin(selected_races)]  # keep only rows where race matches one of the selected categories
brooklyn_offense_by_race_filtered = brooklyn_filtered.pivot_table(index="OFFENSE_DESCRIPTION", columns="RACE", values="SUMMONS_KEY", aggfunc="count", fill_value=0)  # reshape data so each selected race is a column, each offense is a row, and cells show the count of summonses
print(brooklyn_offense_by_race_filtered.head(20))  # display the first 20 rows of the filtered side-by-side comparison table

RACE                                                BLACK  BLACK HISPANIC  \
OFFENSE_DESCRIPTION
ACCEPT ON HAIL                                        244               1
AFTER HOURS CONSUMPTION                                 0               1
AGG. UNLICENSED OPER.                                 637              65
AGGRESSIVE PANHANDLING                                 11               0
AGGRESSIVE PANHANDLING OF MOTOR VEHICLE OR AGGR...      1               0
AIR PISTOL/RIFLE; SELL OR POSSESS                      20               0
ALCOHOL BEVERAGE; CONSUME WHILE DRIVING/OCCUPYING       1               0
ALCOHOL IN THE PARK                                   141              54
ALCOHOL, UNDER INFLUENCE OF (MAY ENDANGER ANYON...      9               1
ALCOHOLIC BEVERAGE IN PUBLIC                         7106             994
ALCOHOLIC BEVERAGE; CONSUME/POSSESS WITH INTENT...     52               9
ALLOW ALCOHOL OUTSIDE                                   2               0
ALLOW GAMBLING                                          0               1
ALLOW GAMBLING - INSIDE BILLIARD HALL                   2               0
AMMUNITION; UNLAWFUL SALE/PURCHASE                      9               0
ANIMAL BEING A NUISANCE                                 1               0
ANIMAL/DOG IN PLAYGROUND/PICNIC AREA                    1               0
APPROPRIATE DRIVER'S LICENSE                            1               0
AUTHORIZED FIRE; NOT PROPERLY CONTAINED                 1               0
AUTHORIZED FIRE; NOT UNDER CONTINUOUS CARE (PER...      4               0

RACE                                                WHITE HISPANIC
OFFENSE_DESCRIPTION
ACCEPT ON HAIL                                                   0
AFTER HOURS CONSUMPTION                                         13
AGG. UNLICENSED OPER.                                          123
AGGRESSIVE PANHANDLING                                           2
AGGRESSIVE PANHANDLING OF MOTOR VEHICLE OR AGGR...               1
AIR PISTOL/RIFLE; SELL OR POSSESS                                8
ALCOHOL BEVERAGE; CONSUME WHILE DRIVING/OCCUPYING                1
ALCOHOL IN THE PARK                                            252
ALCOHOL, UNDER INFLUENCE OF (MAY ENDANGER ANYON...              16
ALCOHOLIC BEVERAGE IN PUBLIC                                  3714
ALCOHOLIC BEVERAGE; CONSUME/POSSESS WITH INTENT...              74
ALLOW ALCOHOL OUTSIDE                                            3
ALLOW GAMBLING                                                   5
ALLOW GAMBLING - INSIDE BILLIARD HALL                            0
AMMUNITION; UNLAWFUL SALE/PURCHASE                               1
ANIMAL BEING A NUISANCE                                          0
ANIMAL/DOG IN PLAYGROUND/PICNIC AREA                             0
APPROPRIATE DRIVER'S LICENSE                                     0
AUTHORIZED FIRE; NOT PROPERLY CONTAINED                          2
AUTHORIZED FIRE; NOT UNDER CONTINUOUS CARE (PER...               0

# Takeaways
Black and Hispanic in brooklyn receive the highest rate of summons based from catagories such as having Alcohol in Public, Recklass driving,and consumig Alcohol